---
version: '3'

services:

  base:
    build: ./cnt/base

  vault:
    image: vault:0.6.5
    hostname: vault
    volumes:
      - "./srv/vault/config:/config"
    command: "vault server --config /config/vault-init.conf"
    cap_add:
      - IPC_LOCK

  cli:
    build: ./cnt/base
    environment:
      - "VAULT_ADDR=http://vault:8200"
    depends_on: 
      - vault
    
  concourse-db:
    image: postgres:9.5
    volumes: ['database:/database']
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
    restart: on-failure:10

  concourse-web:
    image: concourse/concourse
    command: web
    ports: ['8080:8080']
    volumes: ['web-keys:/concourse-keys']
    depends_on: [keys, concourse-db]
    extra_hosts: ['dockerhost:$DOCKERHOST']
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: colthreepv
      CONCOURSE_BASIC_AUTH_PASSWORD: allthewin
      CONCOURSE_EXTERNAL_URL: http://dockerhost:8080
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: on-failure:10

  concourse-worker:
    image: concourse/concourse
    privileged: true
    command: worker
    depends_on: [keys]
    volumes: ['worker-keys:/concourse-keys']
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_ADDRESS: concourse-worker
      CONCOURSE_BAGGAGECLAIM_ADDRESS: concourse-worker
      CONCOURSE_GARDEN_FORWARD_ADDRESS: concourse-worker
      CONCOURSE_BAGGAGECLAIM_FORWARD_ADDRESS: concourse-worker
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: on-failure:10

  keys:
    build: ./cnt/concourse-keys/
    volumes:
      - web-keys:/keys/web
      - worker-keys:/keys/worker

volumes:
  database:    { external: { name: concourse-db } }
  web-keys:    { external: { name: concourse-web-keys } }
  worker-keys: { external: { name: concourse-worker-keys } }